qidb:
  build: ./
  command: 'docker/rails/start-server.sh'
  volumes:
    - ./app
  ports:
    - "3000:3000"
  links:
    - mysql:db
  environment:
    - MONGODB_HOST=db
  volumes_from:
    - bundle
mongo:
  build: ./docker/mongo
bundle:
  image: busybox
  volumes:
    - /bundle
