version: '3.0'
services:
  qidb:
    build: ./
    command: '/app/docker/rails/start-server.sh'
    volumes:
      - .:/app:cached
      - bundle:/app/vendor/bundle
    ports:
      - "3000:3000"
    links:
      - mongo:db
    environment:
      - MONGODB_HOST=db
  mongo:
    build: ./docker/mongo

volumes:
  bundle:
